### ISSUE TITLE
Do I need to create a Nintendo Account if I never had an account before?

### ISSUE THREAD

**Issue by holygamer** [noahc3/Homebrew-Guide#95]
Your guide said this:

"Users with EU Nintendo Network accounts have the option of enabling GDPR protections in their account settings. Doing so has been confirmed to disable lots of telemetry that can get you banned. This setting will not appear if your account is not from the EU.

Go to https://accounts.nintendo.com/setting
Login with your NNID
Under ‘Other settings’, Edit ‘Usage information’ and set it to ‘Don’t share’."

I've never had an account so do I still need to create an account because the Nintendo create account page says it's just for Wii U or Nintendo 3DS. I'll be blocking online access to Nintendo on the Switch via DNS settings like your guide said. 

I also read a comment from someone who said you need an account to play some local multiplayer games, is that correct?

If I need an account then after I create one, when do I sign into it on the Switch? 

Won't I get banned if I'm connecting to Nintendo's servers by signing in? Thanks

**Comment by noahc3** [comment]
Sorry for taking so long to respond!

If you don't have an account and don't plan to create one, you can skip this step. I'll update the guide to mention this.

It sounds like you're on the NNID creation page, thats a legacy account system only used for 3DS and WiiU. Nintendo accounts for Switch (referred to as a "Nintendo Account", thanks Nintendo) can be made here: https://accounts.nintendo.com/. 

It's possible some games need an account to play over LAN or adhoc, I'm not sure.

The guide expects you to have been signed in to your Nintendo account on your sysMMC (your normal Switch OS) before hacking. Then, if you don't plan to do anything incriminating ([see here](https://switch.homebrew.guide/faq.html#what-actions-can-get-me-banned) for what can get you banned), you do not need to setup 90DNS or create an emuMMC as explained in the guide. 

If you do plan on doing things that are incriminating, then you would setup 90DNS, create an emuMMC (copy of your Switch OS on the SD card) cloned from your sysMMC, then remove 90DNS from your sysMMC. This way you can use your sysMMC for normal activities that won't get you banned (legal games, online play, etc), and your emuMMC for things that would normally get you banned (but won't actually get you banned since Nintendo servers would be blocked by 90DNS).

Hope this helps, let me know if there's anything else that isn't clear.
